kind: pipeline
name: default
type: docker

steps:
  - name: load_secret
    image: debian:buster-slim
    volumes:
      - name: ssh
        path: /root/.ssh/
    environment:
      SSH_KEY:
        from_secret: gitea_id_ed25519
    commands:
      - mkdir -p $HOME/.ssh/
      - echo "$SSH_KEY" | base64 -d > $HOME/.ssh/id_ed25519
      - ls $HOME/.ssh/
      - cat $HOME/.ssh/id_ed25519

  - name: build-ci
    image: rustlang/rust:nightly
    volumes:
    - name: ssh
      path: /root/.ssh/
    commands:
     - cargo build -p ci
     - cp target/debug/ci /drone/src/ci

  - name: build
    image: docker:dind
    volumes:
      - name: ssh
        path: /root/.ssh/
      - name: dockersock
        path: /var/run
    commands:
      - /drone/src/ci
    environment:
      DOCKER_BUILDKIT: 1
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    depends_on:
      - "load_secret"

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
  - name: ssh
    temp: {}
  - name: dockersock
    temp: {}
