/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.20.0+rc0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FilesResponse : FilesResponse contains information about multiple files from a repo



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FilesResponse {
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<Box<crate::models::FileCommitResponse>>,
    #[serde(rename = "files", skip_serializing_if = "Option::is_none")]
    pub files: Option<Vec<crate::models::ContentsResponse>>,
    #[serde(rename = "verification", skip_serializing_if = "Option::is_none")]
    pub verification: Option<Box<crate::models::PayloadCommitVerification>>,
}

impl FilesResponse {
    /// FilesResponse contains information about multiple files from a repo
    pub fn new() -> FilesResponse {
        FilesResponse {
            commit: None,
            files: None,
            verification: None,
        }
    }
}


