/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.20.0+rc0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IssueConfig {
    #[serde(rename = "blank_issues_enabled", skip_serializing_if = "Option::is_none")]
    pub blank_issues_enabled: Option<bool>,
    #[serde(rename = "contact_links", skip_serializing_if = "Option::is_none")]
    pub contact_links: Option<Vec<crate::models::IssueConfigContactLink>>,
}

impl IssueConfig {
    pub fn new() -> IssueConfig {
        IssueConfig {
            blank_issues_enabled: None,
            contact_links: None,
        }
    }
}


