/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.20.0+rc0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LabelTemplate : LabelTemplate info of a Label template



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LabelTemplate {
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "exclusive", skip_serializing_if = "Option::is_none")]
    pub exclusive: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl LabelTemplate {
    /// LabelTemplate info of a Label template
    pub fn new() -> LabelTemplate {
        LabelTemplate {
            color: None,
            description: None,
            exclusive: None,
            name: None,
        }
    }
}


