/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.20.0+rc0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NewIssuePinsAllowed : NewIssuePinsAllowed represents an API response that says if new Issue Pins are allowed



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NewIssuePinsAllowed {
    #[serde(rename = "issues", skip_serializing_if = "Option::is_none")]
    pub issues: Option<bool>,
    #[serde(rename = "pull_requests", skip_serializing_if = "Option::is_none")]
    pub pull_requests: Option<bool>,
}

impl NewIssuePinsAllowed {
    /// NewIssuePinsAllowed represents an API response that says if new Issue Pins are allowed
    pub fn new() -> NewIssuePinsAllowed {
        NewIssuePinsAllowed {
            issues: None,
            pull_requests: None,
        }
    }
}


