[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
gitea_client.workspace = true

anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
dotenv.workspace = true
axum.workspace = true
